project_id = "qrizwahrwfinggrspfqg"

[functions.ai-diagnose]
verify_jwt = false

[functions.dental-analyze]
verify_jwt = false

[functions.dental-chat]
verify_jwt = false

[functions.translate]
verify_jwt = false